version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - /tmp/mysql.sock:/var/lib/mysql/data
    environment:
      - MYSQL_USER: root
      - MYSQL_DATABASE: protospace_31677_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/www/
    #environment:
    #  - BUNDLE_PATH=/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true